from training.general import train_one_epoch

from training.train_attention_boosting import train_attention_boosting
from training.train_basic_nn import train_basic_nn
from training.train_fed_avg import train_fed_avg
from training.train_smart_attention import train_smart_attention
